# Generated by Django 5.2.11 on 2026-04-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolcontact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schoolcontact',
            name='school',
        ),
        migrations.DeleteModel(
            name='MagicLinkToken',
        ),
        migrations.DeleteModel(
            name='SchoolContact',
        ),
    ]
