from django.urls import path

from community.api.views import (
    approve_suggestion_view,
    delete_image_view,
    pending_suggestions_view,
    pin_image_view,
    reject_suggestion_view,
    reorder_images_view,
    school_images_view,
    school_photo_upload_view,
    school_suggestions_view,
    update_image_caption_view,
)

urlpatterns = [
    path(
        "schools/<str:moe_code>/suggestions/",
        school_suggestions_view,
        name="school-suggestions",
    ),
    path(
        "schools/<str:moe_code>/suggestions/photo/",
        school_photo_upload_view,
        name="school-photo-upload",
    ),
    path(
        "suggestions/pending/",
        pending_suggestions_view,
        name="suggestions-pending",
    ),
    path(
        "suggestions/<int:pk>/approve/",
        approve_suggestion_view,
        name="suggestion-approve",
    ),
    path(
        "suggestions/<int:pk>/reject/",
        reject_suggestion_view,
        name="suggestion-reject",
    ),
    path(
        "schools/<str:moe_code>/images/reorder/",
        reorder_images_view,
        name="reorder-images",
    ),
    path(
        "schools/<str:moe_code>/images/<int:image_id>/pin/",
        pin_image_view,
        name="pin-image",
    ),
    path(
        "schools/<str:moe_code>/images/<int:image_id>/caption/",
        update_image_caption_view,
        name="update-image-caption",
    ),
    path(
        "schools/<str:moe_code>/images/<int:image_id>/",
        delete_image_view,
        name="delete-image",
    ),
    path(
        "schools/<str:moe_code>/images/",
        school_images_view,
        name="school-images",
    ),
]
