# Generated by Django 5.2.11 on 2026-02-28 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_add_boundary_wkt'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('brevo_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_emails', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('source', models.CharField(choices=[('SATELLITE', 'Satellite (Google Static Maps)'), ('STREET_VIEW', 'Street View'), ('PLACES', 'Google Places'), ('MANUAL', 'Manual Upload')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('attribution', models.CharField(blank=True, default='', max_length=500)),
                ('photo_reference', models.CharField(blank=True, default='', help_text='Google Places photo_reference for re-fetching.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='schools.school')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
