# Generated by Django 5.2.11 on 2026-03-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolimage',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='schoolimage',
            name='photo_reference',
            field=models.CharField(blank=True, default='', help_text='Google Places photo_reference for re-fetching.', max_length=1000),
        ),
    ]
