# Generated by Django 5.2.11 on 2026-03-11 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('outreach', '0002_increase_photo_field_lengths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolimage',
            options={'ordering': ['position', '-is_primary', '-created_at']},
        ),
        migrations.AddField(
            model_name='schoolimage',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Display order (0 = auto, lower = first)'),
        ),
        migrations.AddField(
            model_name='schoolimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='schoolimage',
            name='source',
            field=models.CharField(choices=[('SATELLITE', 'Satellite (Google Static Maps)'), ('STREET_VIEW', 'Street View'), ('PLACES', 'Google Places'), ('MANUAL', 'Manual Upload'), ('COMMUNITY', 'Community Upload')], max_length=20),
        ),
    ]
