# Generated by Django 5.2.11 on 2026-04-25 15:28

import outreach.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_add_position_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolimage',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Bytes stored in Supabase Storage (Sprint 13).', null=True, upload_to=outreach.models.SchoolImage._upload_to),
        ),
        migrations.AlterField(
            model_name='schoolimage',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Legacy field for Sprint 8.2 era images stored as Google Places URLs. New images use image_file (Sprint 13). Kept nullable for migration.', max_length=1000),
        ),
    ]
