# Generated by Django 5.2.11 on 2026-04-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_add_image_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolimage',
            name='caption',
            field=models.CharField(blank=True, default='', help_text='Optional human-written caption shown in the lightbox + image manager (Sprint 15).', max_length=200),
        ),
    ]
