# Generated by Django 5.2.11 on 2026-02-25 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('mp_name', models.CharField(blank=True, default='', max_length=100)),
                ('mp_party', models.CharField(blank=True, default='', max_length=100)),
                ('mp_coalition', models.CharField(blank=True, default='', max_length=50)),
                ('indian_population', models.IntegerField(blank=True, null=True)),
                ('indian_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_income', models.IntegerField(blank=True, null=True)),
                ('poverty_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gini', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('unemployment_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'constituencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DUN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('adun_name', models.CharField(blank=True, default='', max_length=100)),
                ('adun_party', models.CharField(blank=True, default='', max_length=100)),
                ('adun_coalition', models.CharField(blank=True, default='', max_length=50)),
                ('indian_population', models.IntegerField(blank=True, null=True)),
                ('indian_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duns', to='schools.constituency')),
            ],
            options={
                'verbose_name': 'DUN',
                'verbose_name_plural': 'DUNs',
                'ordering': ['code'],
                'unique_together': {('code', 'constituency')},
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('moe_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=150)),
                ('name_tamil', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('postcode', models.CharField(blank=True, default='', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('ppd', models.CharField(blank=True, default='', help_text='Pejabat Pendidikan Daerah (District Education Office)', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('fax', models.CharField(blank=True, default='', max_length=30)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_verified', models.BooleanField(default=False)),
                ('enrolment', models.IntegerField(default=0)),
                ('preschool_enrolment', models.IntegerField(default=0)),
                ('special_enrolment', models.IntegerField(default=0)),
                ('teacher_count', models.IntegerField(default=0)),
                ('grade', models.CharField(blank=True, default='', max_length=10)),
                ('assistance_type', models.CharField(blank=True, default='', max_length=50)),
                ('session_count', models.IntegerField(default=1)),
                ('session_type', models.CharField(blank=True, default='', max_length=20)),
                ('skm_eligible', models.BooleanField(default=False)),
                ('location_type', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.constituency')),
                ('dun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.dun')),
            ],
            options={
                'ordering': ['moe_code'],
            },
        ),
    ]
