# Generated by Django 5.2.11 on 2026-02-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='boundary_wkt',
            field=models.TextField(blank=True, default='', help_text='Boundary polygon in OGC WKT format. Computed by unioning DUN boundaries.'),
        ),
        migrations.AddField(
            model_name='dun',
            name='boundary_wkt',
            field=models.TextField(blank=True, default='', help_text='Boundary polygon in OGC WKT format from Political Constituencies CSV.'),
        ),
    ]
