# Generated by Django 5.2.11 on 2026-03-02 11:11

from django.db import migrations


def apply_proper_case(apps, schema_editor):
    """Apply proper case, phone formatting, email lowercasing to all schools."""
    from schools.utils import to_proper_case, format_phone

    School = apps.get_model("schools", "School")

    for school in School.objects.all():
        school.name = to_proper_case(school.name)
        school.short_name = to_proper_case(school.short_name)
        school.state = to_proper_case(school.state)
        school.ppd = to_proper_case(school.ppd)
        school.address = to_proper_case(school.address)
        school.city = to_proper_case(school.city)
        school.email = school.email.lower() if school.email else ""
        school.phone = format_phone(school.phone)
        school.fax = format_phone(school.fax)
        school.save()


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_add_boundary_wkt"),
    ]

    operations = [
        migrations.RunPython(apply_proper_case, reverse_noop),
    ]
