# Generated by Django 5.2.11 on 2026-03-02 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_proper_case_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('board_chair', 'Board Chairman'), ('headmaster', 'Headmaster'), ('pta_chair', 'PTA Chairman'), ('alumni_chair', 'Alumni Association Chairman')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='schools.school')),
            ],
            options={
                'ordering': ['role'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'role'), name='unique_active_role_per_school')],
            },
        ),
    ]
