# Generated by Django 5.2.11 on 2026-03-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_fix_ymha_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='bank_account_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
