# Generated by Django 5.2.11 on 2026-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_add_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='ge15_indian_voter_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of Indian voters in GE15 (from undi.info)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='ge15_total_voters',
            field=models.IntegerField(blank=True, help_text='Total registered/eligible voters in GE15 (2022)', null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='ge15_winning_margin',
            field=models.IntegerField(blank=True, help_text='Vote margin between winner and runner-up in GE15 (2022)', null=True),
        ),
    ]
