# Generated by Django 5.2.11 on 2026-03-06

"""Normalise abbreviated place names in School.name and School.short_name.

MOE data uses abbreviations inconsistently:
- Ldg (95 schools) vs Ladang (198 schools)
- Sg (17) vs Sungai (22)
- Bkt (2) vs Bukit (19)
- Kg (3) vs Kampung (2)

Hansard text uses the full words. Standardise to full form so alias matching works.
"""

import re

from django.db import migrations


# Word-boundary-safe replacements: (pattern, replacement)
REPLACEMENTS = [
    (r"\bLdg\b", "Ladang"),
    (r"\bSg\b", "Sungai"),
    (r"\bBkt\b", "Bukit"),
    (r"\bKg\b", "Kampung"),
]


def expand_abbreviations(apps, schema_editor):
    School = apps.get_model("schools", "School")
    updated = 0
    for school in School.objects.all():
        new_name = school.name
        new_short = school.short_name or ""
        changed = False
        for pattern, replacement in REPLACEMENTS:
            new_name_2 = re.sub(pattern, replacement, new_name)
            new_short_2 = re.sub(pattern, replacement, new_short)
            if new_name_2 != new_name or new_short_2 != new_short:
                new_name = new_name_2
                new_short = new_short_2
                changed = True
        if changed:
            school.name = new_name
            school.short_name = new_short
            school.save(update_fields=["name", "short_name"])
            updated += 1
    print(f"\n  Normalised {updated} school names (Ldg->Ladang, Sg->Sungai, Bkt->Bukit, Kg->Kampung)")


def contract_abbreviations(apps, schema_editor):
    """Reverse: put abbreviations back (best-effort)."""
    School = apps.get_model("schools", "School")
    REVERSE = [
        (r"\bLadang\b", "Ldg"),
        (r"\bSungai\b", "Sg"),
        (r"\bBukit\b", "Bkt"),
        (r"\bKampung\b", "Kg"),
    ]
    # Only reverse schools that currently have the full form where MOE had abbreviation
    # This is imperfect but acceptable for a reverse migration
    for school in School.objects.all():
        new_name = school.name
        new_short = school.short_name or ""
        changed = False
        for pattern, replacement in REVERSE:
            new_name_2 = re.sub(pattern, replacement, new_name)
            new_short_2 = re.sub(pattern, replacement, new_short)
            if new_name_2 != new_name or new_short_2 != new_short:
                new_name = new_name_2
                new_short = new_short_2
                changed = True
        if changed:
            school.name = new_name
            school.short_name = new_short
            school.save(update_fields=["name", "short_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_add_ge15_election_fields"),
    ]

    operations = [
        migrations.RunPython(expand_abbreviations, contract_abbreviations),
    ]
