# Generated by Django 5.2.11 on 2026-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_normalize_school_abbreviations'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When a school admin first claimed this page via @moe.edu.my sign-in', null=True),
        ),
    ]
