# Generated by Django 5.2.11 on 2026-04-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_drop_magic_link_and_add_claimed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='last_verified',
        ),
        migrations.RemoveField(
            model_name='school',
            name='verified_by',
        ),
    ]
