# Generated by Django 5.2.15 on 2026-06-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_normalise_leader_phones_with_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='school',
            name='history_source_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='history_status',
            field=models.CharField(blank=True, choices=[('UNVERIFIED', 'Unverified — drawn from public sources'), ('SCHOOL_REVIEWED', 'Reviewed by school admin'), ('VERIFIED', 'Verified by SUPERADMIN')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='history_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
