# Generated by Django 5.2.15 on 2026-06-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_add_school_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='history_key_dates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
