# Generated by Django 5.2.15 on 2026-06-28 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_school_history_key_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEnrolmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True)),
                ('students', models.IntegerField()),
                ('source', models.CharField(blank=True, default='', help_text="Origin file or 'live' for the current-DB snapshot.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment_snapshots', to='schools.school')),
            ],
            options={
                'ordering': ['snapshot_date'],
                'unique_together': {('school', 'snapshot_date')},
            },
        ),
    ]
