# Generated by Django 5.2.15 on 2026-07-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_schoolenrolmentsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='ppd',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Pejabat Pendidikan Daerah (District Education Office)', max_length=100),
        ),
    ]
