# Generated by Django 5.2.15 on 2026-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_audit_2026_07_01_hot_path_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolleader',
            name='data_source',
            field=models.CharField(blank=True, default='', help_text='Origin of this record (e.g., TF_2018 for Tamil Foundation 2018)', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolleader',
            name='data_source_date',
            field=models.DateField(blank=True, help_text='When this data was collected', null=True),
        ),
    ]
