# Generated by Django 5.2.11 on 2026-02-25 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HansardSitting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitting_date', models.DateField(db_index=True, unique=True)),
                ('session', models.CharField(blank=True, default='', max_length=50)),
                ('meeting_number', models.CharField(blank=True, default='', max_length=50)),
                ('pdf_url', models.URLField(max_length=500)),
                ('pdf_filename', models.CharField(max_length=200)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('mention_count', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sitting_date'],
            },
        ),
        migrations.CreateModel(
            name='HansardMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('verbatim_quote', models.TextField()),
                ('context_before', models.TextField(blank=True, default='')),
                ('context_after', models.TextField(blank=True, default='')),
                ('keyword_matched', models.CharField(blank=True, default='', max_length=100)),
                ('mp_name', models.CharField(blank=True, default='', max_length=100)),
                ('mp_constituency', models.CharField(blank=True, default='', max_length=100)),
                ('mp_party', models.CharField(blank=True, default='', max_length=100)),
                ('mention_type', models.CharField(blank=True, default='', max_length=20)),
                ('significance', models.IntegerField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, default='', max_length=20)),
                ('change_indicator', models.CharField(blank=True, default='', max_length=20)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('ai_raw_response', models.JSONField(blank=True, default=dict)),
                ('review_status', models.CharField(blank=True, default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sitting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='hansard.hansardsitting')),
            ],
            options={
                'ordering': ['sitting', 'page_number'],
            },
        ),
    ]
