# Generated by Django 5.2.11 on 2026-02-25 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionedSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100 confidence score', max_digits=5)),
                ('matched_by', models.CharField(choices=[('EXACT', 'Exact alias match'), ('TRIGRAM', 'Trigram similarity'), ('MANUAL', 'Manual review')], default='EXACT', max_length=20)),
                ('matched_text', models.CharField(blank=True, default='', help_text='The text fragment that was matched', max_length=200)),
                ('needs_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_schools', to='hansard.hansardmention')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hansard_matches', to='schools.school')),
            ],
            options={
                'unique_together': {('mention', 'school')},
            },
        ),
        migrations.CreateModel(
            name='SchoolAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=200)),
                ('alias_normalized', models.CharField(db_index=True, max_length=200)),
                ('alias_type', models.CharField(choices=[('OFFICIAL', 'Official MOE name'), ('SHORT', 'Short name'), ('MALAY', 'Malay translation'), ('COMMON', 'Common variant'), ('HANSARD', 'Found in Hansard')], default='COMMON', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'school aliases',
                'unique_together': {('school', 'alias_normalized')},
            },
        ),
    ]
