# Generated by Django 5.2.11 on 2026-03-05 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0003_enable_pg_trgm'),
        ('parliament', '0002_meeting_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='hansardsitting',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sittings', to='parliament.parliamentarymeeting'),
        ),
    ]
