# Generated by Django 5.2.11 on 2026-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0004_meeting_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='hansardmention',
            name='speaker_verified',
            field=models.BooleanField(default=True),
        ),
    ]
