# Generated by Django 5.2.11 on 2026-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0006_add_eval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hansardmention',
            name='pipeline_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
