# Generated by Django 5.2.15 on 2026-06-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0011_kathumba_jawa_lane_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hansardsitting',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('NO_PDF', 'No PDF available')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
