# Generated by Django 5.2.15 on 2026-07-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0013_pleton_and_sri_seri_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hansardmention',
            name='mp_constituency',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hansardmention',
            name='review_status',
            field=models.CharField(blank=True, db_index=True, default='PENDING', max_length=20),
        ),
    ]
