# Generated by Django 5.2.15 on 2026-07-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansard', '0014_audit_2026_07_01_hot_path_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hansardmention',
            name='chamber',
            field=models.CharField(choices=[('MAIN', 'Dewan Rakyat'), ('KAMAR_KHAS', 'Kamar Khas (Special Chamber)')], db_index=True, default='MAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='hansardsitting',
            name='kamar_khas_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
