# Generated by Django 5.2.11 on 2026-03-01 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0001_initial'),
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='broadcastrecipient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='broadcastrecipient',
            constraint=models.UniqueConstraint(fields=('broadcast', 'subscriber'), name='unique_broadcast_subscriber'),
        ),
    ]
