# Generated by Django 5.2.11 on 2026-03-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0002_alter_broadcastrecipient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='hero_image',
            field=models.BinaryField(blank=True, default=b'', help_text='Hero image PNG bytes for email header'),
        ),
    ]
