# Generated by Django 5.2.11 on 2026-03-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0003_add_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='hero_image',
            field=models.BinaryField(blank=True, default=b'', help_text='Hero image PNG bytes for email header', null=True),
        ),
    ]
