# Generated by Django 5.2.11 on 2026-03-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0004_allow_null_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastrecipient',
            name='bounce_type',
            field=models.CharField(blank=True, choices=[('HARD', 'Hard Bounce'), ('SOFT', 'Soft Bounce')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broadcastrecipient',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('BOUNCED', 'Bounced'), ('SPAM', 'Spam Complaint'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
