# Generated by Django 5.2.11 on 2026-04-21 15:39

import re
from datetime import datetime

from django.db import migrations, models

# Matches digest subject format: "News Watch — 16 Mar 2026 – 30 Mar 2026"
# Accepts em dash, en dash, or hyphen as the date separator.
SUBJECT_DATE_RE = re.compile(
    r"News Watch\s*[\u2014\u2013\-]\s*"
    r"(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})\s*[\u2013\u2014\-]\s*"
    r"(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})"
)
MONTHS = {
    "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6,
    "Jul": 7, "Aug": 8, "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12,
}


def _parse_digest_coverage(subject):
    """Extract (start, end) dates from a News Watch digest subject.

    Returns (date, date) or (None, None) if unparseable.
    """
    m = SUBJECT_DATE_RE.search(subject or "")
    if not m:
        return None, None
    try:
        start = datetime(
            int(m.group(3)), MONTHS[m.group(2)[:3].title()], int(m.group(1)),
        ).date()
        end = datetime(
            int(m.group(6)), MONTHS[m.group(5)[:3].title()], int(m.group(4)),
        ).date()
        return start, end
    except (KeyError, ValueError):
        return None, None


def backfill_kind_and_coverage(apps, schema_editor):
    Broadcast = apps.get_model("broadcasts", "Broadcast")

    for broadcast in Broadcast.objects.all():
        category = (broadcast.audience_filter or {}).get("category", "")
        subject = broadcast.subject or ""

        if subject.startswith("URGENT:"):
            broadcast.kind = "URGENT_ALERT"
        elif category == "MONTHLY_BLAST":
            broadcast.kind = "MONTHLY_BLAST"
        elif category == "PARLIAMENT_WATCH":
            broadcast.kind = "PARLIAMENT_WATCH"
        elif category == "NEWS_WATCH":
            broadcast.kind = "NEWS_DIGEST"
            start, end = _parse_digest_coverage(subject)
            broadcast.coverage_start_date = start
            broadcast.coverage_end_date = end
        else:
            broadcast.kind = "OTHER"

        broadcast.save(update_fields=[
            "kind", "coverage_start_date", "coverage_end_date",
        ])


def reverse_backfill(apps, schema_editor):
    # Reverse is a no-op; the dropped columns disappear with the schema change.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0005_brevo_webhook_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='coverage_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='coverage_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='kind',
            field=models.CharField(choices=[('NEWS_DIGEST', 'News Digest'), ('URGENT_ALERT', 'Urgent Alert'), ('MONTHLY_BLAST', 'Monthly Blast'), ('PARLIAMENT_WATCH', 'Parliament Watch'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.RunPython(backfill_kind_and_coverage, reverse_backfill),
    ]
