# Generated by Django 5.2.11 on 2026-06-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0006_add_kind_and_coverage_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10),
        ),
    ]
