# Generated by Django 5.2.15 on 2026-07-04 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0007_alter_broadcast_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='broadcast',
            constraint=models.UniqueConstraint(condition=models.Q(('coverage_end_date__isnull', False), ('coverage_start_date__isnull', False), ('status__in', ['SENT', 'SENDING'])), fields=('kind', 'coverage_start_date', 'coverage_end_date'), name='unique_broadcast_per_kind_coverage'),
        ),
    ]
