# Generated by Django 5.2.15 on 2026-07-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcasts', '0008_audit_2026_07_01_unique_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='kind',
            field=models.CharField(choices=[('NEWS_DIGEST', 'News Digest'), ('URGENT_ALERT', 'Urgent Alert'), ('MONTHLY_BLAST', 'Monthly Blast'), ('PARLIAMENT_WATCH', 'Parliament Watch'), ('WELCOME', 'Welcome'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
