# Generated by Django 5.2.11 on 2026-03-04 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_phone', models.CharField(blank=True, default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('bill_code', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('redirected', 'Redirected to Toyyib'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('toyyib_refno', models.CharField(blank=True, default='', max_length=100)),
                ('toyyib_reason', models.CharField(blank=True, default='', max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
