# Generated by Django 5.2.11 on 2026-03-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2000, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('source_name', models.CharField(blank=True, default='', help_text='Publication name (e.g. The Star, Malaysiakini)', max_length=200)),
                ('alert_title', models.CharField(blank=True, default='', help_text='Google Alerts feed title that surfaced this article', max_length=500)),
                ('published_date', models.DateTimeField(blank=True, help_text='Article publication date from RSS or extraction', null=True)),
                ('body_text', models.TextField(blank=True, default='', help_text='Extracted article body text (plain text, no HTML)')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('EXTRACTED', 'Extracted'), ('FAILED', 'Failed')], db_index=True, default='NEW', max_length=10)),
                ('extraction_error', models.TextField(blank=True, default='', help_text='Error message if extraction failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
