# Generated by Django 5.2.11 on 2026-03-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='ai_raw_response',
            field=models.JSONField(blank=True, default=dict, help_text='Raw Gemini response for audit'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated 2-3 sentence summary'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_urgent',
            field=models.BooleanField(db_index=True, default=False, help_text='Flagged for rapid response (closure threat, crisis, etc.)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='mentioned_schools',
            field=models.JSONField(blank=True, default=list, help_text='List of school names/codes mentioned (AI-extracted)'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='relevance_score',
            field=models.IntegerField(blank=True, help_text='AI relevance to Tamil schools (1-5, 5 = highly relevant)', null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('MIXED', 'Mixed')], default='', help_text='AI-assessed sentiment towards Tamil schools', max_length=10),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='urgent_reason',
            field=models.CharField(blank=True, default='', help_text='AI explanation of why this is urgent', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('EXTRACTED', 'Extracted'), ('FAILED', 'Failed'), ('ANALYSED', 'Analysed')], db_index=True, default='NEW', max_length=10),
        ),
    ]
