# Generated by Django 5.2.15 on 2026-07-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newswatch', '0002_add_ai_analysis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Article publication date from RSS or extraction', null=True),
        ),
    ]
