# Generated by Django 5.2.11 on 2026-03-01 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('organisation', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='False when unsubscribed.')),
                ('unsubscribe_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PARLIAMENT_WATCH', 'Parliament Watch'), ('NEWS_WATCH', 'News Watch'), ('MONTHLY_BLAST', 'Monthly Intelligence Blast')], max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('subscriber', 'category')},
            },
        ),
    ]
