# Generated by Django 5.2.11 on 2026-03-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='donor_status',
            field=models.CharField(blank=True, default='', help_text='Original membership status from import.', max_length=30),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source',
            field=models.CharField(blank=True, default='', help_text='How they were added: WEBSITE, BULK_IMPORT, etc.', max_length=30),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='source_tag',
            field=models.CharField(blank=True, default='', help_text='Sub-category: Thulivellam, Member, etc.', max_length=50),
        ),
    ]
