# Generated by Django 5.2.11 on 2026-03-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_add_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='bounce_count',
            field=models.PositiveIntegerField(default=0, help_text='Hard bounce count. Auto-deactivated at 3.'),
        ),
    ]
