# Generated by Django 5.2.15 on 2026-07-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_brevo_webhook_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='school_name',
            field=models.CharField(blank=True, default='', help_text='School they are associated with (if applicable).', max_length=300),
        ),
    ]
