# Generated by Django 5.2.15 on 2026-07-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_subscriber_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='primary_governance_role',
            field=models.CharField(blank=True, default='', help_text='Primary role: Headmaster, Board Chairman, PTA Chairman, or Alumni Chairman.', max_length=100),
        ),
    ]
