# Generated by Django 5.2.11 on 2026-02-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hansard', '0003_enable_pg_trgm'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SittingBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('summary_html', models.TextField(help_text='Rendered HTML from markdown summary')),
                ('social_post_text', models.TextField(blank=True, default='', help_text='Social media post text, max 280 chars')),
                ('email_draft_html', models.TextField(blank=True, default='', help_text='Email newsletter draft')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sitting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='hansard.hansardsitting')),
            ],
            options={
                'ordering': ['-sitting__sitting_date'],
            },
        ),
        migrations.CreateModel(
            name='MPScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(max_length=100)),
                ('party', models.CharField(blank=True, default='', max_length=100)),
                ('coalition', models.CharField(blank=True, default='', max_length=50)),
                ('total_mentions', models.IntegerField(default=0)),
                ('substantive_mentions', models.IntegerField(default=0, help_text='Mentions with significance >= 3')),
                ('questions_asked', models.IntegerField(default=0, help_text='Mentions with type QUESTION')),
                ('commitments_made', models.IntegerField(default=0, help_text='Mentions with type COMMITMENT or sentiment PROMISING')),
                ('last_mention_date', models.DateField(blank=True, null=True)),
                ('school_count', models.IntegerField(default=0, help_text='Number of SJK(T) schools in this constituency')),
                ('total_enrolment', models.IntegerField(default=0, help_text='Total enrolment across constituency schools')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecards', to='schools.constituency')),
            ],
            options={
                'ordering': ['-total_mentions'],
                'unique_together': {('mp_name', 'constituency')},
            },
        ),
    ]
