# Generated by Django 5.2.11 on 2026-03-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParliamentaryMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. First Meeting of the Fourth Term 2025', max_length=200)),
                ('short_name', models.CharField(help_text='e.g. 1st Meeting 2025', max_length=50)),
                ('term', models.PositiveIntegerField(help_text='Parliamentary term (4 = 2025, 5 = 2026)')),
                ('session', models.PositiveIntegerField(help_text='Meeting number within term (1, 2, 3, or 0 for Special)')),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField(help_text='First sitting date')),
                ('end_date', models.DateField(help_text='Last sitting date')),
                ('report_html', models.TextField(blank=True, default='', help_text='Gemini-generated 7-point meeting report (HTML)')),
                ('executive_summary', models.TextField(blank=True, default='', help_text='First 2-3 paragraphs for preview/cards')),
                ('social_post_text', models.TextField(blank=True, default='', help_text='280-char social summary')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('term', 'session', 'year')},
            },
        ),
    ]
