# Generated by Django 5.2.11 on 2026-03-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0003_seed_meetings'),
        ('schools', '0006_add_bank_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('party', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('service_centre_address', models.TextField(blank=True, null=True)),
                ('parlimen_profile_id', models.CharField(blank=True, default='', max_length=20)),
                ('mymp_slug', models.CharField(blank=True, default='', max_length=200)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('constituency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp', to='schools.constituency')),
            ],
            options={
                'verbose_name': 'MP',
                'verbose_name_plural': 'MPs',
            },
        ),
    ]
