# Generated by Django 5.2.11 on 2026-03-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0004_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentarymeeting',
            name='illustration',
            field=models.BinaryField(blank=True, default=b'', help_text='Gemini-generated editorial cartoon (PNG bytes)'),
        ),
    ]
