# Generated by Django 5.2.11 on 2026-03-07 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0005_add_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentarymeeting',
            name='quality_flag',
            field=models.CharField(blank=True, default='', help_text='Quality assessment: GREEN/AMBER/RED (empty = not evaluated)', max_length=10),
        ),
        migrations.AddField(
            model_name='sittingbrief',
            name='quality_flag',
            field=models.CharField(blank=True, default='', help_text='Quality assessment: GREEN/AMBER/RED (empty = not evaluated)', max_length=10),
        ),
        migrations.CreateModel(
            name='QualityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('brief', 'Sitting Brief'), ('report', 'Meeting Report')], max_length=20)),
                ('prompt_version', models.CharField(max_length=20)),
                ('model_used', models.CharField(max_length=50)),
                ('attempt_number', models.IntegerField()),
                ('verdict', models.CharField(choices=[('PASS', 'Pass'), ('FIX', 'Fix'), ('REJECT', 'Reject')], max_length=10)),
                ('tier1_results', models.JSONField(default=dict)),
                ('tier2_scores', models.JSONField(default=dict)),
                ('tier3_flags', models.JSONField(default=dict)),
                ('corrections_applied', models.JSONField(default=list)),
                ('quality_flag', models.CharField(choices=[('GREEN', 'Green'), ('AMBER', 'Amber'), ('RED', 'Red')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_logs', to='parliament.parliamentarymeeting')),
                ('sitting_brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_logs', to='parliament.sittingbrief')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
