# Generated by Django 5.2.11 on 2026-03-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0006_parliamentarymeeting_quality_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='portfolio',
            field=models.CharField(blank=True, default='', help_text="Ministerial portfolio, e.g. 'Minister of Education'", max_length=200),
        ),
    ]
