# Generated by Django 5.2.11 on 2026-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0007_add_mp_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='parliamentarymeeting',
            name='pipeline_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sittingbrief',
            name='pipeline_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
