# Generated by Django 5.2.11 on 2026-03-11 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userprofile'),
        ('schools', '0008_normalize_school_abbreviations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DATA_CORRECTION', 'Data Correction'), ('PHOTO_UPLOAD', 'Photo Upload'), ('NOTE', 'Note')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('field_name', models.CharField(blank=True, default='', max_length=50)),
                ('current_value', models.TextField(blank=True, default='')),
                ('suggested_value', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('image', models.BinaryField(blank=True, default=b'')),
                ('review_note', models.TextField(blank=True, default='')),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to='accounts.userprofile')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
