# Generated by Django 5.2.11 on 2026-04-26 01:20

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_suggestion_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='image',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='pending_image',
            field=models.ImageField(blank=True, help_text='Validated bytes for PHOTO_UPLOAD (Supabase Storage). Cleared on approve (copied to SchoolImage) or reject.', null=True, upload_to=community.models._pending_upload_to),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='phash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Perceptual hash for dedup. Computed at upload time.', max_length=32),
        ),
    ]
