# Generated by Django 5.2.11 on 2026-03-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=200, unique=True)),
                ('gmail_thread_id', models.CharField(blank=True, default='', max_length=200)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField()),
                ('source_broadcast_type', models.CharField(blank=True, default='', max_length=30)),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CORRECTION', 'Correction'), ('TIP', 'Tip'), ('COMPLAINT', 'Complaint'), ('PRAISE', 'Praise'), ('QUESTION', 'Question'), ('UNSUBSCRIBE', 'Unsubscribe'), ('IRRELEVANT', 'Irrelevant')], default='UNCLASSIFIED', max_length=20)),
                ('classification_reasoning', models.TextField(blank=True, default='')),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_RESPONDED', 'Auto-responded'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('auto_response_text', models.TextField(blank=True, default='')),
                ('escalated', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
